package br.edu.uepb.personalcollections.telas;

import br.edu.uepb.personalcollections.Emprestimo;
import br.edu.uepb.personalcollections.ListaDeDesejo;
import br.edu.uepb.personalcollections.excecoes.PersonalCollectionsException;
import br.edu.uepb.personalcollections.gerenciador.Gerenciador;
import br.edu.uepb.personalcollections.util.MyData;
import java.io.IOException;
import java.text.ParseException;
import java.util.Collections;
import java.util.GregorianCalendar;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * Tela principal da aplicação
 *
 * @author Douglas Rafael
 */
public class TelaPrincipal extends javax.swing.JFrame {

    private static final long serialVersionUID = 8641010221981182804L;
    private DefaultTableModel modelTableEmprestimo;
    private DefaultTableModel modelTableListaDeDesejo;

    /**
     * Construtor da TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        modelTableEmprestimo = (DefaultTableModel) table_emprestimos.getModel();
        modelTableListaDeDesejo = (DefaultTableModel) table_lista_desejo.getModel();
        refresh();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lb_total_itens = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_emprestimos = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lb_preco_total = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_lista_desejo = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        bt_ranking = new javax.swing.JButton();
        bt_series = new javax.swing.JButton();
        bt_lista = new javax.swing.JButton();
        bt_emprestimo = new javax.swing.JButton();
        bt_amigos = new javax.swing.JButton();
        bt_itens = new javax.swing.JButton();
        tf_editar_cadastro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Personal Collections");
        setIconImage(new ImageIcon("images/logo.png").getImage());
        setResizable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Itens Com Empréstimo Vencido"));

        jLabel1.setText("Total de Empréstimos Vencidos: ");

        lb_total_itens.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lb_total_itens.setText("00");

        table_emprestimos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        table_emprestimos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Tipo do Item", "Amigo", "Data do Empréstimo", "Data Para Devolução", "Dias em Atraso"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(table_emprestimos);
        if (table_emprestimos.getColumnModel().getColumnCount() > 0) {
            table_emprestimos.getColumnModel().getColumn(1).setPreferredWidth(50);
            table_emprestimos.getColumnModel().getColumn(4).setResizable(false);
            table_emprestimos.getColumnModel().getColumn(5).setPreferredWidth(40);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_total_itens)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_total_itens)
                    .addComponent(jLabel1))
                .addGap(0, 16, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Itens da Minha Lista de Desejo Disponíveis Para Compra"));

        jLabel2.setText("Preço Total dos Itens Disponíveis Para Compra R$:");

        lb_preco_total.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_preco_total.setText("00.00");

        table_lista_desejo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        table_lista_desejo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Título do Item", "Tipo do Item", "Data de Lançamento", "Site Para Compra", "Preço"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_lista_desejo.setToolTipText("Duplo clique para abrir o site de compra caso exista.");
        table_lista_desejo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                abrirUrl(evt);
            }
        });
        jScrollPane1.setViewportView(table_lista_desejo);
        if (table_lista_desejo.getColumnModel().getColumnCount() > 0) {
            table_lista_desejo.getColumnModel().getColumn(4).setPreferredWidth(70);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_preco_total)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_preco_total)
                    .addComponent(jLabel2)))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        bt_ranking.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bt_ranking.setIcon(new ImageIcon("images/ranking.png"));
        bt_ranking.setText("Ranking");
        bt_ranking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirRanking(evt);
            }
        });

        bt_series.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bt_series.setIcon(new ImageIcon("images/series.png"));
        bt_series.setText("Séries");
        bt_series.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirSeries(evt);
            }
        });

        bt_lista.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bt_lista.setIcon(new ImageIcon("images/whishlist.png"));
        bt_lista.setText("Lista de Desejos");
        bt_lista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirListaDeDesejo(evt);
            }
        });

        bt_emprestimo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bt_emprestimo.setIcon(new ImageIcon("images/loan.png"));
        bt_emprestimo.setText("Empréstimos");
        bt_emprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirEmprestimos(evt);
            }
        });

        bt_amigos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bt_amigos.setIcon(new ImageIcon("images/friend.png"));
        bt_amigos.setText("Amigos");
        bt_amigos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirTelaAmigos(evt);
            }
        });

        bt_itens.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bt_itens.setIcon(new ImageIcon("images/items.png"));
        bt_itens.setText("Itens");
        bt_itens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirTelaItens(evt);
            }
        });

        tf_editar_cadastro.setForeground(new java.awt.Color(102, 102, 102));
        tf_editar_cadastro.setText("Editar Cadastro");
        tf_editar_cadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tf_editar_cadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                abrirCadastroUsuario(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_itens)
                .addGap(18, 18, 18)
                .addComponent(bt_amigos)
                .addGap(18, 18, 18)
                .addComponent(bt_emprestimo)
                .addGap(18, 18, 18)
                .addComponent(bt_ranking)
                .addGap(18, 18, 18)
                .addComponent(bt_series)
                .addGap(18, 18, 18)
                .addComponent(bt_lista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 238, Short.MAX_VALUE)
                .addComponent(tf_editar_cadastro)
                .addGap(20, 20, 20))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bt_amigos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bt_itens, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bt_emprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bt_lista, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bt_series, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bt_ranking, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tf_editar_cadastro))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Abre Tela Itens.
     *
     * @param evt
     */
    private void abrirTelaItens(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirTelaItens
        new TelaItens(this, true).setVisible(true);
    }//GEN-LAST:event_abrirTelaItens

    /**
     * Abre Tela Amigos.
     *
     * @param evt
     */
    private void abrirTelaAmigos(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirTelaAmigos
        new TelaAmigos(this, true).setVisible(true);
    }//GEN-LAST:event_abrirTelaAmigos

    /**
     * Abre Tela Emprestimos.
     *
     * @param evt
     */
    private void abrirEmprestimos(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirEmprestimos
        new TelaCadastroEmprestimo(this, true).setVisible(true);
    }//GEN-LAST:event_abrirEmprestimos

    /**
     * Abre Tela Ranking.
     *
     * @param evt
     */
    private void abrirRanking(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirRanking
        new TelaRanking(this, true).setVisible(true);
    }//GEN-LAST:event_abrirRanking

    /**
     * Abre Tela CadastroUsuario.
     *
     * @param evt
     */
    private void abrirCadastroUsuario(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abrirCadastroUsuario
        new TelaCadastroUsuario(this, true).setVisible(true);
    }//GEN-LAST:event_abrirCadastroUsuario

    /**
     * Abre Tela de Series.
     *
     * @param evt
     */
    private void abrirSeries(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirSeries
        new TelaSeries(this, true).setVisible(true);
    }//GEN-LAST:event_abrirSeries

    /**
     * Abre Tela ListaDeDesejo.
     *
     * @param evt
     */
    private void abrirListaDeDesejo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirListaDeDesejo
        new TelaListaDeDesejo(this, true).setVisible(true);
    }//GEN-LAST:event_abrirListaDeDesejo

    /**
     * Abre url se existir.
     *
     * @param evt
     */
    private void abrirUrl(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abrirUrl
        if (evt.getClickCount() == 2) { // Se foi um duplo clique
            try {
                String url_open = (String) table_lista_desejo.getValueAt(table_lista_desejo.getSelectedRow(), 3);
                if (!url_open.isEmpty()) {
                    java.awt.Desktop.getDesktop().browse(java.net.URI.create(url_open));
                }
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "Ocorreu um erro ao tentar abrir URL", "ERRO", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_abrirUrl

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    /**
     * Atualiza todos os componentes da interface principal.
     *
     */
    public void refresh() {
        montaTabelaEmprestimo();
        montaTabelaListaDeDesejo();
    }

    /**
     * Monta tabela de emprestimso vencidos
     *
     */
    private void montaTabelaEmprestimo() {
        try {
            modelTableEmprestimo.setNumRows(0); // Zera a tabela

            Gerenciador manager = new Gerenciador();
            // Monta tabela de emprestimos vencidos
            List<Emprestimo> listaDeEmprestimosVencidos = manager.listarEmprestimosVencidos();
            if (!listaDeEmprestimosVencidos.isEmpty()) {
                for (Emprestimo e : listaDeEmprestimosVencidos) {
                    int dias = MyData.diferencaDias(MyData.stringToCalendar(e.getDataRetono()), new GregorianCalendar());
                    String diasEmAtraso = "";
                    if (dias == 0) {
                        diasEmAtraso = "Se vence hoje!";
                    } else {
                        diasEmAtraso = String.format("%02d dia(s)", Math.abs(dias));
                    }
                    Object[] o = {e.getItem().getTitulo(), e.getItem().getTipo(), e.getAmigo().getNome(), e.getDataEmprestimo(), e.getDataRetono(), diasEmAtraso};
                    modelTableEmprestimo.addRow(o);
                }
                // Seta o total de empréstimos em atraso
                lb_total_itens.setText(String.valueOf(listaDeEmprestimosVencidos.size()));
            }
        } catch (PersonalCollectionsException ex) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro ao tentar preenchertabelas...", "ERRO", JOptionPane.ERROR_MESSAGE);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro ao tentar manipular as datas...", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * Monta tabela de lista de desejo
     *
     */
    private void montaTabelaListaDeDesejo() {
        try {
            modelTableListaDeDesejo.setNumRows(0); // Zera a tabela

            Gerenciador manager = new Gerenciador();
            // Monta tabela de emprestimos vencidos
            List<ListaDeDesejo> listaDeDesejoDisponivel = manager.listarListaDeDesejoDisponiveis();
            if (!listaDeDesejoDisponivel.isEmpty()) {
                double precoTotal = 0.0;
                for (ListaDeDesejo l : listaDeDesejoDisponivel) {
                    String dataLancamento = "";
                    int dias = MyData.diferencaDias(MyData.stringToCalendar(l.getDataDeLancamento()), new GregorianCalendar());
                    if (dias == 0) {
                        dataLancamento = l.getDataDeLancamento() + " - Hoje";
                    } else {
                        dataLancamento = l.getDataDeLancamento() + String.format(" - Há %02d dia(s)", dias);
                    }
                    
                    Object[] o = {l.getItem().getTitulo(), l.getItem().getTipo().getTitulo(), dataLancamento, l.getUrlDeCompra(), String.format("%.2f", l.getItem().getPrecoDeCompra())};
                    precoTotal += l.getItem().getPrecoDeCompra();
                    modelTableListaDeDesejo.addRow(o);
                }
                // Seta o total do valor dos itens disponivel para compra
                lb_preco_total.setText(String.format("%.2f", precoTotal));
            }
        } catch (PersonalCollectionsException ex) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro ao tentar preenchertabelas...", "ERRO", JOptionPane.ERROR_MESSAGE);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro ao tentar manipular as datas...", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_amigos;
    private javax.swing.JButton bt_emprestimo;
    private javax.swing.JButton bt_itens;
    private javax.swing.JButton bt_lista;
    private javax.swing.JButton bt_ranking;
    private javax.swing.JButton bt_series;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lb_preco_total;
    private javax.swing.JLabel lb_total_itens;
    private javax.swing.JTable table_emprestimos;
    private javax.swing.JTable table_lista_desejo;
    private javax.swing.JLabel tf_editar_cadastro;
    // End of variables declaration//GEN-END:variables
}
