/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.uepb.personalcollections.telas;

import br.edu.uepb.personalcollections.Game;
import br.edu.uepb.personalcollections.HQ;
import br.edu.uepb.personalcollections.Item;
import br.edu.uepb.personalcollections.ListaDeDesejo;
import br.edu.uepb.personalcollections.Midia;
import br.edu.uepb.personalcollections.Tabuleiro;
import br.edu.uepb.personalcollections.enums.TipoItem;
import static br.edu.uepb.personalcollections.enums.TipoItem.HQ;
import br.edu.uepb.personalcollections.excecoes.PersonalCollectionsException;
import br.edu.uepb.personalcollections.excecoes.ValidacaoException;
import br.edu.uepb.personalcollections.gerenciador.Gerenciador;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Douglas
 */
public class TelaCadastroListaDeDesejo extends javax.swing.JDialog {

    private static final long serialVersionUID = 8849363978759790991L;
    private Item item;
    private Gerenciador manager;

    /**
     * Creates new form TelaCadastroListaDeDesejo
     */
    public TelaCadastroListaDeDesejo(java.awt.Frame parent, boolean modal, Item item) {
        super(parent, modal);
        initComponents();
        manager = new Gerenciador();
        this.item = item;

        if (item != null) {
            populaItem(item);
            bt_editar.setEnabled(true);
        } else {
            tf_data_lacamento.setSelectedDate(null);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        cb_tipoItem = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bt_novo_item = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        tf_data_lacamento = new datechooser.beans.DateChooserCombo();
        jLabel6 = new javax.swing.JLabel();
        tf_site_compra = new javax.swing.JTextField();
        bt_inserir = new javax.swing.JButton();
        bt_cancelar = new javax.swing.JButton();
        panel_dados = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lb_titulo = new javax.swing.JLabel();
        lb_tipo = new javax.swing.JLabel();
        lb_nota = new javax.swing.JLabel();
        lb_preco = new javax.swing.JLabel();
        lb_obs = new javax.swing.JLabel();
        bt_editar = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Lista de Desejo");
        setIconImage(new ImageIcon("images/logo.png").getImage());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                fecharJanela(evt);
            }
        });

        cb_tipoItem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cb_tipoItem.setModel(new DefaultComboBoxModel(TipoItem.values()));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Tipo do Item");

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("(Selecione o tipo de item que deseja incluir a sua Lista de Desejos...)");

        bt_novo_item.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bt_novo_item.setIcon(new ImageIcon("images/new.png"));
        bt_novo_item.setText("Inserir Item");
        bt_novo_item.setToolTipText("");
        bt_novo_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserirNovoItem(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Data de Lançamento");

        tf_data_lacamento.setCurrentView(new datechooser.view.appearance.AppearancesList("Swing",
            new datechooser.view.appearance.ViewAppearance("custom",
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    true,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(128, 128, 128),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(255, 0, 0),
                    false,
                    false,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                (datechooser.view.BackRenderer)null,
                false,
                true)));
    tf_data_lacamento.setFieldFont(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 12));

    jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel6.setText("Site de Compra");

    tf_site_compra.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    tf_site_compra.setMargin(new java.awt.Insets(2, 5, 2, 2));

    bt_inserir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    bt_inserir.setIcon(new ImageIcon("images/save.png"));
    bt_inserir.setText("Salvar");
    bt_inserir.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            salvar(evt);
        }
    });

    bt_cancelar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    bt_cancelar.setIcon(new ImageIcon("images/cancel.png"));
    bt_cancelar.setText("Cancelar");
    bt_cancelar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            cancelar(evt);
        }
    });

    panel_dados.setBorder(javax.swing.BorderFactory.createTitledBorder("Resumo do Item a Ser Cadastrado"));

    jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel7.setText("Título:");

    jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel8.setText("Tipo do Item:");

    jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel9.setText("Nota:");

    jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel10.setText("Preço R$:");

    jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel11.setText("Observação:");

    lb_titulo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    lb_titulo.setForeground(new java.awt.Color(102, 102, 102));
    lb_titulo.setText("__");

    lb_tipo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    lb_tipo.setForeground(new java.awt.Color(102, 102, 102));
    lb_tipo.setText("__");

    lb_nota.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    lb_nota.setForeground(new java.awt.Color(102, 102, 102));
    lb_nota.setText("__");

    lb_preco.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    lb_preco.setForeground(new java.awt.Color(102, 102, 102));
    lb_preco.setText("__");

    lb_obs.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    lb_obs.setForeground(new java.awt.Color(102, 102, 102));
    lb_obs.setText("__");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lb_titulo)
                .addComponent(lb_tipo)
                .addComponent(lb_nota)
                .addComponent(lb_preco)
                .addComponent(lb_obs))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(lb_titulo)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(lb_tipo)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(lb_nota)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(lb_preco)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(lb_obs)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout panel_dadosLayout = new javax.swing.GroupLayout(panel_dados);
    panel_dados.setLayout(panel_dadosLayout);
    panel_dadosLayout.setHorizontalGroup(
        panel_dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(panel_dadosLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(panel_dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel7)
                .addComponent(jLabel9)
                .addComponent(jLabel10)
                .addComponent(jLabel8)
                .addComponent(jLabel11))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addContainerGap())
    );
    panel_dadosLayout.setVerticalGroup(
        panel_dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(panel_dadosLayout.createSequentialGroup()
            .addGap(12, 12, 12)
            .addComponent(jLabel7)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel8)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel9)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel10)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel11)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_dadosLayout.createSequentialGroup()
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addContainerGap())
    );

    bt_editar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    bt_editar.setIcon(new ImageIcon("images/edit.png"));
    bt_editar.setMnemonic('E');
    bt_editar.setText("Editar");
    bt_editar.setEnabled(false);
    bt_editar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            editarItem(evt);
        }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(20, 20, 20)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jLabel4)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabel2))
                .addGroup(layout.createSequentialGroup()
                    .addComponent(cb_tipoItem, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(bt_novo_item, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bt_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(bt_inserir, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(tf_data_lacamento, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(282, 282, 282))
                            .addComponent(tf_site_compra))))
                .addComponent(panel_dados, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap(21, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(22, 22, 22)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel4)
                .addComponent(jLabel2))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(cb_tipoItem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(bt_novo_item, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addComponent(panel_dados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel5)
                .addComponent(jLabel6))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(tf_data_lacamento, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(tf_site_compra, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(bt_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_inserir, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(18, Short.MAX_VALUE))
    );

    pack();
    setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Abre tela para cadastro de item de acordo com o tipo escolhido no
     * combobox
     *
     * @param evt
     */
    private void inserirNovoItem(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserirNovoItem
        TipoItem tipoItem = (TipoItem) cb_tipoItem.getSelectedItem();
        this.dispose();
        if (tipoItem.equals(TipoItem.HQ)) {
            TelaCadastroHQ telaHQ = new TelaCadastroHQ(null, true, 0);
            telaHQ.setInterfaceListaDeDesejo(true);
            telaHQ.setVisible(true);
        } else if (tipoItem.equals(TipoItem.MIDIA)) {
            TelaCadastroMidia telaMidia = new TelaCadastroMidia(null, true, 0);
            telaMidia.setInterfaceListaDeDesejo(true);
            telaMidia.setVisible(true);
        } else if (tipoItem.equals(TipoItem.JOGOVIDEOGAME)) {
            TelaCadastroGame telaGame = new TelaCadastroGame(null, true, 0);
            telaGame.setInterfaceListaDeDesejo(true);
            telaGame.setVisible(true);
        } else if (tipoItem.equals(TipoItem.JOGOTABULEIRO)) {
            TelaCadastroTabuleiro telaTabuleiro = new TelaCadastroTabuleiro(null, true, 0);
            telaTabuleiro.setInterfaceListaDeDesejo(true);
            telaTabuleiro.setVisible(true);
        }
    }//GEN-LAST:event_inserirNovoItem

    /**
     * Salva item na lista de desejo.
     *
     * @param evt
     */
    private void salvar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvar
        try {
            if (validaCampos()) {
                manager.inserirItemListaDeDesejo(getInterfaceListaDeDesejo());
                JOptionPane.showMessageDialog(null, "Item: \"" + getInterfaceListaDeDesejo().getItem().getTitulo() + "\" foi adicionado na sua Lista de Desejo com sucesso!", "Inserção", JOptionPane.INFORMATION_MESSAGE);
                fecharJanela(null);
            } else {
                throw new ValidacaoException("O Item que deseja adicionar em sua Lista de Desejo deve ser pré-inserido antes!");
            }
        } catch (ValidacaoException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Problema na validação", JOptionPane.WARNING_MESSAGE);
        } catch (PersonalCollectionsException ex) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro ao tentar atualizar a série...", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_salvar

    /**
     * Fecha janela.
     *
     * @param evt
     */
    private void fecharJanela(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_fecharJanela
        this.dispose();
        new TelaListaDeDesejo(null, true).setVisible(true);
    }//GEN-LAST:event_fecharJanela

    /**
     * Fecha janela.
     *
     * @param evt
     */
    private void cancelar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelar
        fecharJanela(null);
    }//GEN-LAST:event_cancelar

    /**
     * Abre a tela do último item adicionado para edição dos dados
     *
     * @param evt
     */
    private void editarItem(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarItem
        Item o = getItem();
        if (o != null) {
            this.dispose();
            if (o.getTipo().equals(TipoItem.HQ)) {
                TelaCadastroHQ telaHQ = new TelaCadastroHQ(null, true, o.getId());
                telaHQ.setInterfaceListaDeDesejo(true);
                telaHQ.montaAlterarDados((HQ) o);
                telaHQ.setVisible(true);
            } else if (o.getTipo().equals(TipoItem.MIDIA)) {
                TelaCadastroMidia telaMidia = new TelaCadastroMidia(null, true, o.getId());
                telaMidia.setInterfaceListaDeDesejo(true);
                telaMidia.montaAlterarDados((Midia) o);
                telaMidia.setVisible(true);
            } else if (o.getTipo().equals(TipoItem.JOGOVIDEOGAME)) {
                TelaCadastroGame telaGame = new TelaCadastroGame(null, true, o.getId());
                telaGame.setInterfaceListaDeDesejo(true);
                telaGame.montaAlterarDados((Game) o);
                telaGame.setVisible(true);
            } else if (o.getTipo().equals(TipoItem.JOGOTABULEIRO)) {
                TelaCadastroTabuleiro telaTabuleiro = new TelaCadastroTabuleiro(null, true, o.getId());
                telaTabuleiro.setInterfaceListaDeDesejo(true);
                telaTabuleiro.montaAlterarDados((Tabuleiro) o);
                telaTabuleiro.setVisible(true);
            }
        }
    }//GEN-LAST:event_editarItem

    /**
     * Método main.
     *
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroListaDeDesejo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroListaDeDesejo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroListaDeDesejo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroListaDeDesejo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaCadastroListaDeDesejo dialog = new TelaCadastroListaDeDesejo(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    /**
     * Popula o os campos do item com os dados.
     *
     * @param o
     */
    private void populaItem(Item o) {
        lb_titulo.setText(o.getTitulo());
        lb_tipo.setText(o.getTipo().getTitulo());
        lb_nota.setText(String.valueOf(o.getNota()));
        lb_preco.setText(String.valueOf(o.getPrecoDeCompra()));
        lb_obs.setText(o.getObservacao());

    }

    /**
     * Valida campos
     *
     * @return
     */
    private boolean validaCampos() {
        if (getItem() != null) {
            return true;
        } else {
            return false;
        }
    }

    /**
     * Verifica se houve alteração de dados.
     *
     * @return <code>true</code> se houve alteração de dados ou
     * <code>false</code> caso não houve
     */
    private boolean isAlteracao() {
        if (!lb_titulo.equals("")) {
            return true;
        }
        return false;
    }

    /**
     * Recupera o item a ser cadastrado na lista de desejo.
     *
     * @return O item
     */
    public Item getItem() {
        return item;
    }

    /**
     * Seta o item a ser cadastrado na lista de desejo.
     *
     * @param item O item
     */
    public void setItem(Item item) {
        this.item = item;
    }

    /**
     * Recupera da interface grafica o objeto ListaDeDesejo
     *
     * @return o objeto ListaDeDesejo contendo o item a ser inserido
     */
    private ListaDeDesejo getInterfaceListaDeDesejo() {
        return new ListaDeDesejo(tf_data_lacamento.getText(), tf_site_compra.getText(), item);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_cancelar;
    private javax.swing.JButton bt_editar;
    private javax.swing.JButton bt_inserir;
    private javax.swing.JButton bt_novo_item;
    private javax.swing.JComboBox cb_tipoItem;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb_nota;
    private javax.swing.JLabel lb_obs;
    private javax.swing.JLabel lb_preco;
    private javax.swing.JLabel lb_tipo;
    private javax.swing.JLabel lb_titulo;
    private javax.swing.JPanel panel_dados;
    private datechooser.beans.DateChooserCombo tf_data_lacamento;
    private javax.swing.JTextField tf_site_compra;
    // End of variables declaration//GEN-END:variables
}
